id = "kerboscript"
name = "Kerboscript (kOS)"
version = "0.0.1"
schema_version = 1
authors = ["Amatsugu <amatsugu@example.com>"]
description = "kOS/Kerboscript support"

[grammars.kerboscript]
repository = "https://github.com/Amatsugu/zed-kos.git"
rev = "8001b398aa5669177e07de2e016cbbb566fd97ee"

[language_servers.kos-language-server]
name = "kOS Language Server"
languages = ["Kerboscript"]
